### ISSUE TITLE
find(1): -fstype option is unimplemented

### ISSUE THREAD

**Issue by yopito** [chimera-linux/chimerautils#1]
contrary to man find(1), `-fstype` option is unimplemented:
```
root@cbuild: ~$ find . -fstype foo
find: -fstype: unknown primary or operator
```

**Comment by q66** [comment]
the code for this is compiled out, there is no straightforward way to get filesystem type with posix or linux API (best `statfs` on linux will give you is `f_type`, which is one of the file system magic constants and there is no way to get a string out of it other than hardcoding every file system name/magic number), freebsd has `f_fstypename` which just gives you the string, but we unfortunately can't use that

**Comment by yopito** [comment]
thanks for your explanations.
my points:
* `df -t <fstype>` has the same problem
* some notes here: https://github.com/chimera-linux/chimerautils/blob/master/DIFFERENCES#L442, don't know if relevant (not clever enough)
* shouldn't we consider using these magic numbers anyway ? that means import or read them from linux-headers, and add and some code to map numbers/names ?

**Comment by q66** [comment]
i'm not really sure yet how i'll address this, probably via some shared code in libcompat so that if i have to add some ugly code to work around this, it can at least be shared between tools

in any case it's not super high priority for now

**Comment by yopito** [comment]
OK, would be nice via libcompat.
what about this issue ? keep opened as a (long-term) reminder ?

**Comment by q66** [comment]
i fixed `df -t`, the issue can stay open for now though
