### ISSUE TITLE
Logic error in ctrlaltdel.c

### ISSUE THREAD

**Issue by wjk** [chimera-linux/chimerautils#10]
https://github.com/chimera-linux/chimerautils/blob/c661247427e8bf767f8d935ee4287211798581e1/src.custom/ctrlaltdel/ctrlaltdel.c#L122

https://github.com/chimera-linux/chimerautils/blob/c661247427e8bf767f8d935ee4287211798581e1/src.custom/ctrlaltdel/ctrlaltdel.c#L124

These should probably be `fprintf`.

**Comment by q66** [comment]
what, why?

**Comment by wjk** [comment]
Please accept my apologies. I misunderstood the code in question. I thought it was trying to write something to the `ctrl-alt-del` sysfs file, but it is really reading data for output to the user, which should go to stdout. There are no problems here. 😄
