### ISSUE TITLE
bc(1) should be Gavin Howard's bc

### ISSUE THREAD

**Issue by Connor-GH** [chimera-linux/chimerautils#13]
Modern FreeBSD uses Gavin Howard's bc(1), although this is not the one in the source tree. Chimera Linux should use this version. Additionally, you cannot build the Linux kernel from scratch with the default bc due to it using the read() extension, only found on GNU bc(1) and the bc(1) by Gavin Howard.

**Comment by q66** [comment]
what do you mean? we have bc-gh available in the repository for things that cannot use the regular bc, and freebsd does not have bc-gh in the source repo at all (it merely has it in ports)

**Comment by q66** [comment]
as i see it, if you want bc-gh for a downstream, you're free to build it separately, there is no point in bundling it here (in general chimerautils does not bundle auxiliary stuff that has other up to date cleanly buildable upstreams without freebsd patches)

**Comment by Connor-GH** [comment]
FreeBSD's contrib/ folder in the source tree already contains gh-bc, and you already use the implementation of several programs from contrib/, but one example is vis(1): https://github.com/freebsd/freebsd-src/blob/main/contrib/vis/vis.c. You of course use the One True Awk as well: https://github.com/freebsd/freebsd-src/blob/main/contrib/awk

**Comment by Connor-GH** [comment]
This is your solution for the One True Awk: https://github.com/chimera-linux/chimerautils/blob/master/import-src.sh#L236C1-L236C37

Why *shouldn't* this be done for bc as well considering the bc currently used doesn't pass *many* tests, including a kernel ``make``?

**Comment by q66** [comment]
the freebsd contrib directory does not contain bc-gh, i had already checked this several times and it's just not there; bc-gh is only an installation option from ports

one-true-awk is pretty much an exception to th rule as 1) the upstream does not make releases and 2) the codebase freebsd uses is not the master branch verbatim, but rather follows the bsd-features branch; every other software from contrib/ in chimerautils is stuff that is *not* ordinarily packaged standalone on linux

whether the current bc passes kernel build is entirely irrelevant, the kernel build does not allow other bsd utilities either, e.g. sed and make - if i was only allowed to use tools the kernel works out of the box with, I wouldn't be doing any of this in the first place

**Comment by arp242** [comment]
contrib/bc is Gavin's bc, and usr.bin/gh-bc builds that. There's also the older usr.bin/bc but that no longer seems used(?)

Either way, Gavin's version is the default bc it seems, at least on my 13.2 system:

```
[~]% which bc
/usr/bin/bc

[~]% bc --version
bc 6.2.4
Copyright (c) 2018-2023 Gavin D. Howard and contributors
Report bugs at: https://git.gavinhoward.com/gavin/bc

This is free software with ABSOLUTELY NO WARRANTY.
```

I didn't install anything from ports.

**Comment by q66** [comment]
I see - in that case perhaps I should make bc optional in chimerautils (via a meson toggle) since you can build bc-gh on linux separately without any issues (and perhaps chimera should default to it)

**Comment by q66** [comment]
https://github.com/chimera-linux/cports/compare/b741f7ee5014...6434f98cc477
