### ISSUE TITLE
Would getting ee to work be of use?

### ISSUE THREAD

**Issue by anoraktrend** [chimera-linux/chimerautils#20]
For those who want it (me), ee is a very useful piece of software that only relies on a curses implementation. I would love to not have to maintain my own version just so it builds on musl, plus I believe the meson build system would be so much easier to get working than having to deal with the ancient "create.make" script system.

**Comment by q66** [comment]
what's the benefit over say, nano? (which is similarly simple and supports unicode and the likes)

**Comment by anoraktrend** [comment]
The benefit is just the interface, there’s a menu you access via esc. AEE, unfortunately, isn’t as permissively licensed but is quite a bit more useful than ee as a general purpose editor using ncurses.

**Comment by anoraktrend** [comment]
I’m going to update my extraction from fbsd to include a meson build because the create.make script is useful for building stuff cross platform.

**Comment by q66** [comment]
i already imported it here (latest master builds it)
