### ISSUE TITLE
`cp`:  Add Copy on Write (CoW) support for filesystems that support it

### ISSUE THREAD

**Issue by sidkshatriya** [chimera-linux/chimerautils#24]
If you're using a filesystem like btrfs or xfs that supports Copy on Write you can create a really inexpensive and fast copy by doing

`cp --reflink=always <src> <dest>`

(here this is the typical `cp` packaged on systems like fedora -- most probably gnu coreutils)

[On MacOS you can do that same using `cp -c <src> <dest>`]

It would be great if chimerautils could support something like this.

**Comment by q66** [comment]
using reflinks has been the default from the start though? it does not need any specific switches, the copy_file_range syscall comes from bsd and the tools always use it when available

**Comment by q66** [comment]
yes that's what i said
