### ISSUE TITLE
Is Rust based coreutils not an option

### ISSUE THREAD

**Issue by heliocastro** [chimera-linux/chimerautils#4]
Hi, this is not a bug per-se

Just a question why you decided to jump on create your own coreutils instead of using the modern almost 1x1 par rust version of coreutils.
https://github.com/uutils/coreutils/

Anyway, i tried in the past do the similar approach of you, but with rpm based distro. Things are not ready there yet.

Great work, man

**Comment by q66** [comment]
1) i don't want a 1:1 version of gnu coreutils
2) i don't want rust anywhere near the bootstrap path
