### ISSUE TITLE
Can it be built on other systems? 

### ISSUE THREAD

**Issue by StandingPadAnimations** [chimera-linux/chimerautils#5]
I know this is a pretty dumb question, but I'm on Arch and I want to replace GNU utils with BSD. Is it possible to build this on other Linux distros or is it Chimera specific?

**Comment by q66** [comment]
it can build on any distro, but if you try to use it as a drop-in replacement for coreutils/etc in an existing system you're in for a disappointment and/or an unrealistic amount of work
